### PR TITLE
Fix error message when HttpGateway.HttpApi is less than 0

### PR DESCRIPTION
**Pull request by dali99**
This error message was very confusing until I looked at the code :sweat_smile:

### CODE REVIEW

**Comment by dali99** [comment]
This field was also not present in the example config file in the documentation

**Comment by spantaleev** [comment]
Thank you! :+1:

Isn't this field documented here: https://github.com/devture/matrix-corporal/blame/b60da71f133df1cc57bdde7b4e3dc43215d959dd/docs/configuration.md#L80

**Comment by dali99** [comment]
Yep, but not in the "complete" configuration example which was what tripped me up!

**Comment by spantaleev** [comment]
Ah, right! Fixed in 560b86597b172c47ce.

**Pull request merged**
